// Parsers for the ALARA toolkit's own output, so health and running versions
// can be brought across the air gap as text:
//   - .snapshot files   alara_release_snapshot.sh v2.0  (./alara_server.sh snapshot)
//   - status output     alara_server.sh v2.6           (./alara_server.sh status)
//   - doctor output     alara_server.sh v2.6           (./alara_server.sh doctor)
// Formats are taken from the scripts themselves (see lib/fixtures/toolkit,
// generated by running them). Pasted output may or may not carry ANSI colour
// codes; both are accepted.

export type ToolkitKind = 'snapshot' | 'status' | 'doctor';
export type ContainerState = 'running' | 'restarting' | 'exited' | 'paused' | 'created' | 'other';
export type ContainerHealth = 'healthy' | 'unhealthy' | 'starting' | null;

export interface ToolkitContainer {
  name: string;
  service: string | null; // compose service label (status only)
  image: string;
  status: string; // docker's status text, e.g. "Up 3 hours (healthy)"
  ports: string | null; // status only
  state: ContainerState;
  health: ContainerHealth;
}

export interface ParsedSnapshot {
  kind: 'snapshot';
  roleCode: string; // BOT_BUILDER | CHAT_BOT | CHAT_SERVICE
  role: string; // tracker name, e.g. "ChatBot / NLU"
  environment: string; // tracker name: SIT | UAT | Prod
  hostname: string | null;
  generated: string | null; // ISO from "# generated:"
  scriptVersion: string | null;
  containers: ToolkitContainer[];
  envFiles: { file: string; entries: { key: string; value: string; sensitive: boolean }[] }[];
  // Raw non-empty section lines, as alara_release_compare.sh reads them.
  sections: Record<string, string[]>;
}

export interface ParsedStatus {
  kind: 'status';
  role: string;
  environment: string;
  ip: string | null;
  configPoints: string | null; // SIT | UAT | PROD | UNDETERMINED | UNKNOWN
  workdir: string | null;
  envFiles: { file: string; state: 'encrypted' | 'plain' | 'missing'; encryptedValues: number | null }[];
  masterKey: 'present' | 'missing' | null;
  keyState: string | null;
  containers: ToolkitContainer[];
}

export interface ParsedDoctor {
  kind: 'doctor';
  role: string;
  environment: string;
  ip: string | null;
  serverVersion: string | null; // alara_server.sh version, e.g. "2.6"
  runningAs: string | null;
  checks: { status: 'ok' | 'MISS' | 'warn'; item: string }[];
  retired: string[];
  keyState: string | null;
  passed: boolean | null;
}

export type ParsedToolkit = ParsedSnapshot | ParsedStatus | ParsedDoctor;

const ROLE_CODES: Record<string, string> = {
  BOT_BUILDER: 'Bot-Builder',
  CHAT_BOT: 'ChatBot / NLU',
  DATABASE: 'Database',
  CHAT_SERVICE: 'Chat-Service',
};
const ROLE_LABELS = Object.values(ROLE_CODES);

// Same list as alara_release_snapshot.sh v2.0 (substring match, upper-cased).
const SENSITIVE_PATTERNS = [
  'PASSWORD', 'SECRET', 'SECRET_KEY', 'ACCESS_KEY', 'SESSION_KEY', 'MASTER_KEY',
  'API_KEY', 'TOKEN', 'REDIS_URL', 'OMNI_REDIS_URL', 'MONGO_URI', 'MONGODB_URL', 'DATABASE_URL',
];

export function stripAnsi(text: string): string {
  // eslint-disable-next-line no-control-regex
  return text.replace(/\x1b\[[0-9;]*[A-Za-z]/g, '').replace(/\r/g, '');
}

export function trackerEnv(env: string): string {
  const e = env.trim().toUpperCase();
  return e === 'PROD' ? 'Prod' : e;
}

export function trackerRole(roleOrCode: string): string {
  const v = roleOrCode.trim();
  return ROLE_CODES[v.toUpperCase()] ?? (ROLE_LABELS.find((l) => l.toLowerCase() === v.toLowerCase()) || v);
}

export function isSensitiveKey(key: string): boolean {
  const k = key.toUpperCase();
  return SENSITIVE_PATTERNS.some((p) => k.includes(p));
}

export function containerState(status: string): { state: ContainerState; health: ContainerHealth } {
  const s = status.trim();
  const health: ContainerHealth = /\(healthy\)/.test(s)
    ? 'healthy'
    : /\(unhealthy\)/.test(s)
    ? 'unhealthy'
    : /\(health: starting\)/.test(s)
    ? 'starting'
    : null;
  let state: ContainerState = 'other';
  if (/^Up\b/.test(s)) state = /\(Paused\)/i.test(s) ? 'paused' : 'running';
  else if (/^Restarting\b/.test(s)) state = 'restarting';
  else if (/^Exited\b/.test(s)) state = 'exited';
  else if (/^Created\b/.test(s)) state = 'created';
  return { state, health };
}

export function detectKind(text: string): ToolkitKind | null {
  const t = stripAnsi(text);
  if (/^\s*# ALARA_RELEASE_SNAPSHOT\s*$/m.test(t)) return 'snapshot';
  if (/ALARA Doctor/.test(t) || /^\s*Server control\s*:/m.test(t)) return 'doctor';
  if (/^\s*Physical env\s*:/m.test(t)) return 'status';
  return null;
}

// ── .snapshot ────────────────────────────────────────────────────────────────

export function parseSnapshot(text: string): ParsedSnapshot {
  const lines = stripAnsi(text).split('\n');
  if (!lines.some((l) => l === '# ALARA_RELEASE_SNAPSHOT')) {
    throw new Error('Not an ALARA release snapshot (missing "# ALARA_RELEASE_SNAPSHOT" header).');
  }
  const header = (name: string) => {
    // Same as the compare script: grep '^# <name>:' | awk '{print $3}'
    const line = lines.find((l) => l.startsWith(`# ${name}:`));
    return line ? line.split(/\s+/)[2] ?? null : null;
  };
  const roleCode = header('role');
  const envCode = header('environment');
  if (!roleCode || !envCode) throw new Error('Snapshot is missing its "# role:" or "# environment:" header.');
  if (!ROLE_CODES[roleCode]) throw new Error(`Unknown role in snapshot: ${roleCode}`);
  if (!/^(SIT|UAT|PROD)$/.test(envCode)) throw new Error(`Unknown environment in snapshot: ${envCode}`);
  if (roleCode === 'DATABASE') throw new Error('DATABASE snapshots are out of scope (the snapshot tool refuses them too).');

  // Sections: "## NAME" until the next "## " line; blank lines dropped (awk NF).
  const sections: Record<string, string[]> = {};
  const order: string[] = [];
  let current: string | null = null;
  for (const line of lines) {
    if (line.startsWith('## ')) {
      current = line.slice(3);
      if (!sections[current]) {
        sections[current] = [];
        order.push(current);
      }
      continue;
    }
    if (current && line.trim()) sections[current].push(line);
  }

  const containers: ToolkitContainer[] = (sections.IMAGES ?? []).map((l) => {
    const eq = l.indexOf('=');
    const name = eq === -1 ? l : l.slice(0, eq);
    const rest = eq === -1 ? '' : l.slice(eq + 1);
    const bar = rest.indexOf('|');
    const image = bar === -1 ? rest : rest.slice(0, bar);
    const status = bar === -1 ? '' : rest.slice(bar + 1);
    return { name, service: null, image, status, ports: null, ...containerState(status) };
  });

  const envFiles = order
    .filter((s) => s.startsWith('ENV:'))
    .map((s) => ({
      file: s.slice(4),
      entries: sections[s].map((l) => {
        const eq = l.indexOf('=');
        const key = eq === -1 ? l : l.slice(0, eq);
        const value = eq === -1 ? '' : l.slice(eq + 1);
        return { key, value, sensitive: value.startsWith('SHA256:') };
      }),
    }));

  const generatedLine = lines.find((l) => l.startsWith('# generated:'));
  return {
    kind: 'snapshot',
    roleCode,
    role: ROLE_CODES[roleCode],
    environment: trackerEnv(envCode),
    hostname: header('hostname'),
    generated: generatedLine ? generatedLine.slice('# generated:'.length).trim() || null : null,
    scriptVersion: header('script_version'),
    containers,
    envFiles,
    sections,
  };
}

// ── status ───────────────────────────────────────────────────────────────────

const field = (text: string, label: string): string | null => {
  const m = new RegExp(`^\\s*${label}\\s*:\\s*(.*?)\\s*$`, 'm').exec(text);
  return m ? m[1] : null;
};

// Where the PORTS column starts in "<status> <ports>": docker's port forms
// 0.0.0.0:80->80/tcp, :::80->80/tcp, [::]:80->80/tcp, 8000/tcp.
const PORTS_START = /(?:^|\s)((?:\d{1,3}\.){3}\d{1,3}:\d|:::\d|\[::\]:\d|\d+(?:-\d+)?\/(?:tcp|udp|sctp)\b)/;

// Rows are printf'd into fixed widths, but a long value pushes the rest of
// the line right. NAME, SERVICE and IMAGE never contain spaces, so they are
// read as the first three tokens; STATUS and PORTS share the remainder.
function parseContainerRow(line: string, withPorts: boolean): ToolkitContainer | null {
  const m = /^\s*(\S+)\s+(\S+)\s+(\S+)\s+(.*?)\s*$/.exec(line);
  if (!m) return null;
  const [, name, service, image, rest] = m;
  let status = rest;
  let ports: string | null = null;
  if (withPorts) {
    const p = PORTS_START.exec(rest);
    if (p) {
      const at = p.index + (p[0].length - p[1].length);
      status = rest.slice(0, at).trim();
      ports = rest.slice(at).trim() || null;
    }
  }
  return {
    name,
    service: service === '—' ? null : service,
    image,
    status: status.trim(),
    ports,
    ...containerState(status),
  };
}

function containerTable(lines: string[], startMarker: RegExp, withPorts: boolean): ToolkitContainer[] {
  const start = lines.findIndex((l) => startMarker.test(l));
  if (start === -1) return [];
  const out: ToolkitContainer[] = [];
  let seenHeader = false;
  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*──/.test(line)) break; // next section
    if (!line.trim()) {
      if (seenHeader) break;
      continue;
    }
    if (/^\s*NAME\s+SERVICE\s+IMAGE\s+STATUS/.test(line)) {
      seenHeader = true;
      continue;
    }
    if (!seenHeader) continue; // "No containers running." / "None."
    const row = parseContainerRow(line, withPorts);
    if (row) out.push(row);
  }
  return out;
}

export function parseStatus(text: string): ParsedStatus {
  const t = stripAnsi(text);
  const lines = t.split('\n');
  const roleLabel = field(t, 'Role');
  const physical = field(t, 'Physical env');
  if (!roleLabel || !physical) throw new Error('Not alara_server.sh status output (no "Role :" / "Physical env :" lines).');
  const envMatch = /^(SIT|UAT|PROD)\b/.exec(physical);
  if (!envMatch) throw new Error(`Unrecognised environment in status: ${physical}`);
  const ip = /\(IP ([\d.]+)\)/.exec(physical)?.[1] ?? null;

  const envFiles: ParsedStatus['envFiles'] = [];
  for (const line of lines) {
    const m = /^\s{2}(\.?[\w.-]+)\s*:\s*(encrypted \((\d+) values\)|NOT encrypted|MISSING)\s*$/.exec(line);
    if (!m) continue;
    envFiles.push({
      file: m[1],
      state: m[2].startsWith('encrypted') ? 'encrypted' : m[2] === 'MISSING' ? 'missing' : 'plain',
      encryptedValues: m[3] ? Number(m[3]) : null,
    });
  }

  const mk = field(t, 'Master key');
  return {
    kind: 'status',
    role: trackerRole(roleLabel),
    environment: trackerEnv(envMatch[1]),
    ip,
    configPoints: field(t, 'Config points'),
    workdir: field(t, 'Workdir'),
    envFiles,
    masterKey: mk === null ? null : /^present/.test(mk) ? 'present' : 'missing',
    keyState: field(t, 'Key state'),
    containers: [
      ...containerTable(lines, /Running Containers/, true),
      ...containerTable(lines, /Exited Containers/, false),
    ],
  };
}

// ── doctor ───────────────────────────────────────────────────────────────────

export function parseDoctor(text: string): ParsedDoctor {
  const t = stripAnsi(text);
  const roleLabel = field(t, 'Detected role');
  const envLine = field(t, 'Detected env');
  if (!roleLabel || !envLine) throw new Error('Not alara_server.sh doctor output (no "Detected role/env" lines).');
  const envMatch = /^(SIT|UAT|PROD)\b/.exec(envLine);
  if (!envMatch) throw new Error(`Unrecognised environment in doctor: ${envLine}`);

  const checks: ParsedDoctor['checks'] = [];
  const retired: string[] = [];
  for (const line of t.split('\n')) {
    const m = /^\s{2}(ok|MISS|warn)\s{2,}(.+?)\s*$/.exec(line);
    if (!m) continue;
    checks.push({ status: m[1] as 'ok' | 'MISS' | 'warn', item: m[2] });
    const r = /^(\S+) present — RETIRED/.exec(m[2]);
    if (r) retired.push(r[1]);
  }
  const keyLine = /^\s+key\s{2,}(.+?)\s*$/m.exec(t)?.[1] ?? null;
  return {
    kind: 'doctor',
    role: trackerRole(roleLabel),
    environment: trackerEnv(envMatch[1]),
    ip: /from IP ([\d.]+)/.exec(envLine)?.[1] ?? null,
    serverVersion: field(t, 'Server control')?.replace(/^v/, '') ?? null,
    runningAs: field(t, 'Running as'),
    checks,
    retired,
    keyState: keyLine,
    passed: /Preflight passed\./.test(t) ? true : /Preflight FAILED/.test(t) ? false : null,
  };
}

export function parseToolkitOutput(text: string): ParsedToolkit {
  const kind = detectKind(text);
  if (kind === 'snapshot') return parseSnapshot(text);
  if (kind === 'status') return parseStatus(text);
  if (kind === 'doctor') return parseDoctor(text);
  throw new Error('Not recognised: expected a .snapshot file, or the output of ./alara_server.sh status or doctor.');
}
